SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@OLD_COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE TABLE `cars` (
  `car_id` CHAR(5) NOT NULL,
  `car_picture` VARCHAR(255) NOT NULL,
  `brand` VARCHAR(20) NOT NULL,
  `model` VARCHAR(30) NOT NULL,
  `class` VARCHAR(10) NOT NULL,
  `category` VARCHAR(15) NOT NULL,
  `body_type` VARCHAR(15) NOT NULL,
  `price` VARCHAR(50) NOT NULL,
  `fuel_type` VARCHAR(10) NOT NULL,
  `drive` VARCHAR(3) NOT NULL,
  `length` INT(10) NOT NULL,
  `width` INT(10) NOT NULL,
  `height` INT(50) NOT NULL,
  `weight` INT(10) NOT NULL,
  `description_title` TEXT NOT NULL,
  `description` TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `cars`
  ADD PRIMARY KEY (`car_id`);

COMMIT;


/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;